name: Metrics
on:
  schedule:
    # Runs every Monday at 06:00 UTC — adjust as you like
    - cron: "0 6 * * 1"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
     environment: 
       name: METRICS_TOKEN
    steps:
      - uses: lowlighter/metrics@v3.34 # revisa https://github.com/lowlighter/metrics/releases y usa el tag más reciente
        with:
          token: ${{ secrets.METRICS }}}
          user: X4ndre
          template: classic
          filename: Metrics/metrics.svg

          # Core sections of the card
          base: header, activity, community, repositories, metadata

          # Top languages plugin (this is the chart you asked for)
          plugin_languages: yes
          plugin_languages_analysis_type: repository
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

          config_timezone: America/Mexico_City

      - uses: lowlighter/metrics@v3.34 # revisa https://github.com/lowlighter/metrics/releases y usa el tag más reciente
        with:
          token: ${{ secrets.METRICS }}
          user: X4ndre
          template: classic
          filename: Metrics/metrics-calendar.svg

          # Sin "base" para que solo se genere el widget del calendario, nada más
          base: ""

          # Calendario isométrico de contribuciones (el "full year calendar")
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_timezone: America/Mexico_City
