name: Metrics
on:
  schedule:
    - cron: "0 6 * * 1,4"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
       name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS }}
          user: X4ndre
          template: classic
          filename: Metrics/metrics.svg

          
          base: header, activity, community, repositories, metadata

          
          plugin_languages: yes
          plugin_languages_analysis_type: repository
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

          config_timezone: America/Mexico_City

      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS }}
          user: X4ndre
          template: classic
          filename: Metrics/metrics-calendar.svg

         
          base: ""

         
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_timezone: America/Mexico_City
